#######################################################
####  Root Project Settings Spawner Config Object  ####
#######################################################

#projectSettings:
#    kind: tabs
#    groups:
#        datasetsProjectTabGroup: Datasets
#    contains: tabs
#    tabs:
#        projectDatasetsTab:
#            kind: tab
#            label: Saved Datasets
#            group: datasetsProjectTabGroup
#            active: true
#            contents:
#                ${projectDatasetsPanel}
#
#
#projectDatasetsPanel:
#    kind: panel
#    label: Saved Datasets in this Project
#    contents:
#        projectDatasetsContainer:
#            tag: "div#proj-saved-datasets-list-container"
#        projectDatasetsAdminScript:
#            tag: script|src="/scripts/xnat/plugin/datasets/datasets-projectAdmin.js"
